### ISSUE TITLE
Nothing shows up

### ISSUE THREAD

**Issue by jdeluyck** [konnectedvn/lovelace-vertical-slider-cover-card#10]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Home Assistant version:** 
0.114.4
Installed via HACS.

**Browser and Operating System:** 
Linux. Firefox 80.0.1

**Description of problem:**
Installed the module, tried to enable this in a lovelace view, but nothing shows up. Literally nothing. HA isn't showing an error when editing the card that should show stuff, but.. nope.

```
type: 'custom:vertical-slider-cover-card'
background: 'rgba(0, 0, 0, 0.4)'
showButton: true
buttonPath: /lovelace/test
buttonText: Home
countText: covers open
openBaseline: 5
icon: 'mdi:blinds'
iconSize: 40px
panelType: false
showSidebar: false
positionHeight: 300px
positionWidth: 100px
gapWidth: 50px
switchHeight: 80px
switchWidth: 100px
showSwitch: true
sideColor1: '#ffcccc'
sideColor2: '#b30000'
openColor: 'hsl(0, 0%, 20%, 0.8)'
closedColor: 'hsl(0, 0%, 90%)'
title: Covers
titleSize: 40px
entities:
  - entity: cover.kitchen
    name: Left Blinds
  - entity: cover.study
    name: Right Blinds
  - entity: cover.living_room
    name: Basement Shutter

```

**Javascript errors shown in the web inspector (if applicable):**

A lot of these:
```
Uncaught (in promise) TypeError: stateObj is undefined
    _stateCount https://hassio:8123/hacsfiles/lovelace-vertical-slider-cover-card/vertical-slider-cover-card.js:158
    _stateCount https://hassio:8123/hacsfiles/lovelace-vertical-slider-cover-card/vertical-slider-cover-card.js:156
    render https://hassio:8123/hacsfiles/lovelace-vertical-slider-cover-card/vertical-slider-cover-card.js:76
    update https://unpkg.com/lit-element@2.0.1/lit-element.js?module:160
    performUpdate https://unpkg.com/lit-element@2.0.1/lib/updating-element.js?module:475
    _enqueueUpdate https://unpkg.com/lit-element@2.0.1/lib/updating-element.js?module:437
```

**Additional information:**
Blinds report in state open/closed, in attributes only the following:
```
current_position: 100 
friendly_name: Kitchen 
supported_features: 15
```

It's a first try, but I can't really figure out what's going on.
