### ISSUE TITLE
Top to down option

### ISSUE THREAD

**Issue by cben0ist** [konnectedvn/lovelace-vertical-slider-cover-card#2]
**Is your feature request related to a problem? Please describe.**
Not a problem, this is a suggestion

**Describe the solution you'd like**
Windows blinds and garage door are closed when fully down. It would make more sense for a user to slide down to close the cover

**Comment by cben0ist** [comment]
Actually made it work with the color options...

```
  - background: 'rgb(0, 0, 0, 0.4)'
    entities:
      - entity: cover.living_east_blind
        name: Living Blind
      - entity: cover.kitchen_door_blind
        name: Kitchen Blind
    icon: 'mdi:blinds'
    panelType: false
    positionHeight: 250px
    positionWidth: 80px
    switchHeight: 80px
    switchWidth: 80px
    sideColor2: 'rgb(0, 0, 0, 0)'
    sideColor1: 'rgb(51, 180, 235, .6)'
    openColor: 'rgb(51, 180, 235, .85)'
    title: Covers
    type: 'custom:vertical-slider-cover-card'
```
