### ISSUE TITLE
Just does not work

### ISSUE THREAD

**Issue by DrJohnT** [konnectedvn/lovelace-vertical-slider-cover-card#6]
Running on Home Assistant 0.112.3

Installed vertical-slider-cover-card using HACS v0.0.6

Attempted to configure plugin using following in Lovelace UI.  However, 

1. Blinds are not controlled - cannot open or close them
2. Title simply reads "open" when in fact they were partly open, so not getting % open correctly
3. positionHeight simply does not increase height of bar

My YAML below.  Screenshot provided.  Other screenshot is a working set of controls using https://github.com/thomasloven/lovelace-slider-entity-row

```yaml
type: 'custom:vertical-slider-cover-card'
countText: blinds open
icon: 'mdi:blinds'
panelType: true
positionHeight: 800px
positionWidth: 200px
title: Blinds
entities:
  - entity: cover.velux_north_study_blind
    name: Study North
  - entity: cover.velux_south_study_blind
    name: Study South
  - entity: cover.velux_north_bedroom_blind
    name: Bedroom North
  - entity: cover.velux_south_bedroom_blind
    name: Bedroom South
```
![2020-07-11 06_23_38-Overview - Home Assistant](https://user-images.githubusercontent.com/10464775/87217390-95fe0f80-c340-11ea-910d-a7460983563f.png)

![2020-07-11 06_27_06-Overview - Home Assistant](https://user-images.githubusercontent.com/10464775/87217395-9ac2c380-c340-11ea-8a8c-7bc0c54e9210.png)

**Comment by wolverinevn** [comment]
Does your cover show current_position in % or 0-100? Find it on Developer Tools > States.
Any thing weird on your browser console (please open Developer Tools/Menu in your browser).

**Comment by wolverinevn** [comment]
Have you tried to reinstall card then clear browser cache?

**Comment by DrJohnT** [comment]
This is probably why.  Reports "open" and position  is an attribute.  Although my Velux blinds do have a stop feature, does not seem to be present via the Apple HomeKit integration.  My config is documented here, so you can read how I integrated the blinds and windows. https://github.com/DrJohnT/HomeAssistantPublicConfig

![2020-07-11 09_07_55-Developer Tools - Home Assistant](https://user-images.githubusercontent.com/10464775/87219776-21ce6680-c356-11ea-90dc-bb5f676209b5.png)

**Comment by wolverinevn** [comment]
Well documented and organized configurations! I like it but still can't find covers' configurations.
Anyway, I guess supported_features: 7 is the cause of issue.
Please upgrade to v0.0.7 and let me know if the issue still persists!

**Comment by DrJohnT** [comment]
Hey Wolverinevn, I finally got around to trying then new version.  The controls now work so I can open/close the blinds.  Thanks!

Here is my config and questions are on the image.  Key thing is that the button at bottom left hand side does not show.  Also, my blinds don't have a stop feature (at least via the Apple HomeKit interface used by HA).  So would be nice to have a "showStopButton = false" option.



```yaml
type: 'custom:vertical-slider-cover-card'
countText: blinds open
icon: 'mdi:blinds'
panelType: true
showSidebar: true
showButton: true
buttonText: Windows
buttonPath: /lovelace/windows
positionHeight: 400px
positionWidth: 140px
titleSize: 30px
gapWidth: 40px
title: Blinds
openColor: var(--primary-color)
closedColor: var(--primary-background-color)
sideColor1: var(--disabled-color)
sideColor2: var(--divider-color)
switchWidth: 0px
switchHeight: 0px
switchColor: var(--primary-background-color)
entities:
  - entity: cover.velux_north_study_blind
    name: Study North
  - entity: cover.velux_south_study_blind
    name: Study South
  - entity: cover.velux_north_bedroom_blind
    name: Bedroom North
  - entity: cover.velux_south_bedroom_blind
    name: Bedroom South
```

![SecondAttempt](https://user-images.githubusercontent.com/10464775/87664974-0f8d6780-c75e-11ea-9adc-12d5d6fcac1d.png)
