### ISSUE TITLE
Some minor ui changes

### ISSUE THREAD

**Issue by Pirol62** [konnectedvn/lovelace-vertical-slider-cover-card#8]
Hi, when panelType = true then the scroll bar in the bottom isn't necessary.
![image](https://user-images.githubusercontent.com/48820003/88799636-1036ec80-d1a7-11ea-9215-ac961f57347b.png)

Can you set it unvisible then?

is it possible to make the header text sizable:
![image](https://user-images.githubusercontent.com/48820003/88799753-3e1c3100-d1a7-11ea-8128-1690362ac15f.png)

**Comment by wolverinevn** [comment]
+ Scrollbar appears when content is wider than card width (it is fixed by Home Assistant). Please change the size of elements (all options end with 'Width').
+ Cover title font size is calculated from positionWidth and gapWidth. Reduce them will reduce the fontsize.

**Comment by Pirol62** [comment]
Ok, understood the text size.
But this is my config:
````
background: transparent
buttonPath: /lovelace/0
buttonText: Home
closedColor: 'hsl(0, 0%, 90%)'
countText: open
entities:
  - entity: cover.rolladen_wohnzimmer
    name: Wohnzimmer
  - entity: cover.rolladen_kuche
    name: Küche
icon: 'mdi:blinds'
iconSize: 35px
openColor: 'hsl(0, 0%, 20%, 0.8)'
panelType: true
positionHeight: 150px
positionWidth: 100px
showButton: false
sideColor1: var(--primary-color)
sideColor2: var(--primary-background-color)
switchColor: var(--primary-color)
switchHeight: 30px
title: ' '
titleSize: 30px
type: 'custom:vertical-slider-cover-card'
````
This is the picture:
![image](https://user-images.githubusercontent.com/48820003/88887927-9b62c180-d23d-11ea-9d9f-8692b17a1a27.png)
The scrollbar is still there, even there is huge space available ;-)
